// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/beauty-inventory-current/Current.tsx": () => import("../components/mockups/beauty-inventory-current/Current.tsx"),
  "./components/mockups/beauty-inventory-organized/Organized.tsx": () => import("../components/mockups/beauty-inventory-organized/Organized.tsx"),
  "./components/mockups/templates/KnowledgeBasePrototype-p4WIB0/Atlas.tsx": () => import("../components/mockups/templates/KnowledgeBasePrototype-p4WIB0/Atlas.tsx"),
  "./components/mockups/templates/MemphisFurnitureDatingLandingPage-3y779c/App.tsx": () => import("../components/mockups/templates/MemphisFurnitureDatingLandingPage-3y779c/App.tsx"),
  "./components/mockups/templates/MidCenturyBankingLandingPage-5HixXt/App.tsx": () => import("../components/mockups/templates/MidCenturyBankingLandingPage-5HixXt/App.tsx"),
  "./components/mockups/templates/MidCenturyBankingLandingPage-8m6jIj/App.tsx": () => import("../components/mockups/templates/MidCenturyBankingLandingPage-8m6jIj/App.tsx"),
  "./components/mockups/templates/MidCenturyRealEstateChangelog-hWiKni/App.tsx": () => import("../components/mockups/templates/MidCenturyRealEstateChangelog-hWiKni/App.tsx"),
  "./components/mockups/templates/MindfulnessAppLanding-au81SZ/Lp11.tsx": () => import("../components/mockups/templates/MindfulnessAppLanding-au81SZ/Lp11.tsx"),
  "./components/mockups/templates/WeeklyCalendarPrototype-Pc4UgO/Timeblock.tsx": () => import("../components/mockups/templates/WeeklyCalendarPrototype-Pc4UgO/Timeblock.tsx")
};
