import './organized.css';
import { useEffect, useMemo, useRef, useState, type ChangeEvent, type FormEvent } from 'react';
import { Archive, ArrowDownUp, Box, Check, ImagePlus, Plus, Search, SlidersHorizontal, Trash2, X } from 'lucide-react';

type Product = { id: string; name: string; quantity: number; category: string; image?: string };
const STORAGE_KEY = 'beauty-shelf-products';
const CATEGORIES = ['全部', '保養', '彩妝', '清潔', '防曬'];
const tones = ['bg-[hsl(183_45%_80%)]', 'bg-[hsl(7_78%_59%)]', 'bg-[hsl(77_62%_58%)]', 'bg-[hsl(257_55%_86%)]', 'bg-[hsl(42_83%_78%)]'];

function ProductVisual({ product }: { product: Product }) {
  if (product.image) return <img src={product.image} alt={`${product.name} 商品照片`} className="h-full w-full object-cover" />;
  return <div className={`relative flex h-full w-full items-center justify-center overflow-hidden ${tones[product.id.length % tones.length]}`} aria-label={`${product.name} 商品示意圖`}>
    <div className="relative h-24 w-16 rounded-[10px] bg-[hsl(0_0%_98%/.86)] shadow-[8px_12px_18px_hsl(222_35%_17%/.18)]"><div className="absolute left-1/2 top-0 h-3 w-10 -translate-x-1/2 rounded-b bg-[hsl(222_35%_17%/.2)]" /><div className="absolute bottom-7 left-1/2 w-full -translate-x-1/2 text-center text-[8px] font-bold tracking-[.08em] text-[hsl(222_35%_17%/.62)]">BEAUTY</div><div className="absolute bottom-2 left-1/2 h-1 w-7 -translate-x-1/2 rounded-full bg-[hsl(7_78%_59%/.7)]" /></div>
  </div>;
}

function AddSheet({ onAdd, onClose }: { onAdd: (p: Product) => void; onClose: () => void }) {
  const fileRef = useRef<HTMLInputElement>(null); const [name, setName] = useState(''); const [quantity, setQuantity] = useState('1'); const [category, setCategory] = useState('保養'); const [image, setImage] = useState(''); const [error, setError] = useState('');
  const handleFile = (e: ChangeEvent<HTMLInputElement>) => { const file = e.target.files?.[0]; if (!file) return; if (!file.type.startsWith('image/')) { setError('請選擇圖片檔案。'); return; } const reader = new FileReader(); reader.onload = () => { setImage(String(reader.result)); setError(''); }; reader.readAsDataURL(file); };
  const submit = (e: FormEvent) => { e.preventDefault(); if (!name.trim()) { setError('請輸入商品名稱。'); return; } onAdd({ id: `${Date.now()}-${Math.random().toString(36).slice(2)}`, name: name.trim(), quantity: Math.max(0, Math.floor(Number(quantity) || 0)), category, image }); onClose(); };
  return <div className="fixed inset-0 z-40 flex items-end justify-center bg-[hsl(222_35%_17%/.3)] p-0 backdrop-blur-sm sm:items-center sm:p-5" role="presentation" onMouseDown={e => e.target === e.currentTarget && onClose()}><section role="dialog" aria-modal="true" aria-labelledby="add-drawer-title" className="organize-in w-full max-w-lg rounded-t-[28px] bg-[hsl(var(--drawer-panel))] p-5 shadow-2xl sm:rounded-[28px] sm:p-7">
    <div className="mb-5 flex items-center justify-between"><div><p className="text-[10px] font-bold tracking-[.2em] text-[hsl(var(--drawer-coral))]">放進抽屜</p><h2 id="add-drawer-title" className="mt-1 text-xl font-extrabold">新增一件商品</h2></div><button type="button" onClick={onClose} aria-label="關閉新增商品" className="flex h-10 w-10 items-center justify-center rounded-full bg-[hsl(var(--drawer-paper))]"><X size={19} /></button></div>
    <form onSubmit={submit} className="space-y-4"><input ref={fileRef} type="file" accept="image/*" onChange={handleFile} className="sr-only" /><button type="button" onClick={() => fileRef.current?.click()} className="flex h-24 w-full items-center justify-center gap-2 rounded-2xl border border-dashed border-[hsl(var(--drawer-coral)/.5)] bg-[hsl(7_78%_59%/.06)] text-sm font-bold text-[hsl(var(--drawer-coral-dark))]">{image ? <img src={image} alt="商品照片預覽" className="h-full w-full rounded-2xl object-cover" /> : <><ImagePlus size={20} />上傳商品照片</>}</button>
      <div><label htmlFor="drawer-name" className="mb-1.5 block text-xs font-bold">商品名稱</label><input id="drawer-name" value={name} onChange={e => { setName(e.target.value); setError(''); }} placeholder="例如：玻尿酸保濕精華" className="h-11 w-full rounded-xl border border-[hsl(var(--drawer-line))] bg-[hsl(var(--drawer-paper))] px-3.5 text-sm outline-none focus:border-[hsl(var(--drawer-coral))]" /></div>
      <div className="grid grid-cols-2 gap-3"><div><label htmlFor="drawer-quantity" className="mb-1.5 block text-xs font-bold">目前數量</label><input id="drawer-quantity" type="number" min="0" value={quantity} onChange={e => setQuantity(e.target.value)} className="h-11 w-full rounded-xl border border-[hsl(var(--drawer-line))] bg-[hsl(var(--drawer-paper))] px-3.5 text-sm" /></div><div><label htmlFor="drawer-category" className="mb-1.5 block text-xs font-bold">分類</label><select id="drawer-category" value={category} onChange={e => setCategory(e.target.value)} className="h-11 w-full rounded-xl border border-[hsl(var(--drawer-line))] bg-[hsl(var(--drawer-paper))] px-3.5 text-sm">{CATEGORIES.slice(1).map(c => <option key={c}>{c}</option>)}</select></div></div>
      {error && <p role="alert" className="text-xs font-bold text-[hsl(var(--drawer-coral-dark))]">{error}</p>}<button type="submit" className="h-12 w-full rounded-xl bg-[hsl(var(--drawer-coral))] text-sm font-extrabold text-white">放入我的抽屜</button>
    </form></section></div>;
}

function DeleteDialog({ product, onCancel, onConfirm }: { product: Product; onCancel: () => void; onConfirm: () => void }) {
  useEffect(() => { const key = (e: KeyboardEvent) => e.key === 'Escape' && onCancel(); document.addEventListener('keydown', key); return () => document.removeEventListener('keydown', key); }, [onCancel]);
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-[hsl(222_35%_17%/.35)] p-5 backdrop-blur-sm" role="presentation" onMouseDown={e => e.target === e.currentTarget && onCancel()}><div role="dialog" aria-modal="true" aria-labelledby="remove-title" className="organize-in w-full max-w-sm rounded-3xl bg-[hsl(var(--drawer-panel))] p-6 shadow-2xl"><div className="mb-4 flex h-11 w-11 items-center justify-center rounded-2xl bg-[hsl(7_78%_59%/.12)] text-[hsl(var(--drawer-coral))]"><Trash2 size={20} /></div><h2 id="remove-title" className="text-lg font-extrabold">從抽屜移除這件商品？</h2><p className="mt-2 text-sm leading-6 text-[hsl(var(--drawer-muted))]">「{product.name}」將會被刪除，這個動作無法復原。</p><div className="mt-6 flex gap-3"><button type="button" onClick={onCancel} className="h-11 flex-1 rounded-xl border border-[hsl(var(--drawer-line))] text-sm font-bold">先留著</button><button type="button" onClick={onConfirm} className="h-11 flex-1 rounded-xl bg-[hsl(var(--drawer-coral))] text-sm font-bold text-white">確認移除</button></div></div></div>;
}

function ProductTile({ product, onChange, onDelete }: { product: Product; onChange: (n: number) => void; onDelete: () => void }) {
  const empty = product.quantity === 0; return <article className="drawer-card overflow-hidden rounded-[22px] border border-[hsl(var(--drawer-line))] bg-[hsl(var(--drawer-panel))]"><div className="relative aspect-[1.18/1]"><ProductVisual product={product} /><span className={`absolute left-3 top-3 rounded-full px-2 py-1 text-[10px] font-extrabold ${empty ? 'bg-[hsl(var(--drawer-ink))] text-white' : product.quantity <= 2 ? 'bg-[hsl(42_83%_78%)]' : 'bg-[hsl(0_0%_100%/.82)]'}`}>{empty ? '用曬啦' : product.quantity <= 2 ? '快用完' : '使用中'}</span><button type="button" onClick={onDelete} aria-label={`刪除 ${product.name}`} className="absolute right-2.5 top-2.5 flex h-8 w-8 items-center justify-center rounded-full bg-[hsl(0_0%_100%/.86)]"><Trash2 size={15} /></button></div><div className="p-3.5"><div className="flex min-h-[54px] items-start justify-between gap-2"><div><p className="text-[10px] font-bold text-[hsl(var(--drawer-muted))]">{product.category}</p><h3 className="mt-1 text-sm font-extrabold leading-5">{product.name}</h3></div><div className="text-right"><strong className={`block text-2xl font-black leading-none ${empty ? 'text-[hsl(var(--drawer-coral))]' : ''}`}>{product.quantity}</strong><span className="text-[9px] text-[hsl(var(--drawer-muted))]">件</span></div></div><div className="mt-3 grid grid-cols-4 gap-1.5">{[1, 2, 3].map(n => <button key={n} type="button" disabled={empty} onClick={() => onChange(-n)} aria-label={`從${product.name}扣除${n}件`} className="flex h-9 items-center justify-center rounded-lg border border-[hsl(var(--drawer-line))] text-xs font-extrabold disabled:opacity-30">−{n}</button>)}<button type="button" onClick={() => onChange(1)} aria-label={`替${product.name}補貨一件`} className="flex h-9 items-center justify-center rounded-lg bg-[hsl(77_62%_58%/.38)] text-xs font-extrabold">+1</button></div></div></article>;
}

export default function App() {
  const [products, setProducts] = useState<Product[]>(() => { try { return JSON.parse(localStorage.getItem(STORAGE_KEY) || '[]') as Product[]; } catch { return []; } });
  const [query, setQuery] = useState(''); const [category, setCategory] = useState('全部'); const [sheetOpen, setSheetOpen] = useState(false); const [deleteTarget, setDeleteTarget] = useState<Product | null>(null);
  useEffect(() => { localStorage.setItem(STORAGE_KEY, JSON.stringify(products)); }, [products]);
  const filtered = useMemo(() => products.filter(p => (!query.trim() || p.name.toLowerCase().includes(query.trim().toLowerCase())) && (category === '全部' || p.category === category)), [products, query, category]);
  const total = products.reduce((s, p) => s + p.quantity, 0); const low = products.filter(p => p.quantity > 0 && p.quantity <= 2).length;
  const update = (id: string, n: number) => setProducts(ps => ps.map(p => p.id === id ? { ...p, quantity: Math.max(0, p.quantity + n) } : p));
  return <div className="organized-beauty-root drawer-noise min-h-[100dvh] bg-[hsl(var(--drawer-paper))]"><main className="drawer-surface min-h-[100dvh] pb-24"><div className="mx-auto max-w-5xl px-4 pb-10 pt-5 sm:px-7 sm:pt-8"><header className="organize-in flex items-center justify-between"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[hsl(var(--drawer-ink))] text-[hsl(var(--drawer-lime))]"><Box size={20} /></div><div><p className="text-[15px] font-black">我的美妝抽屜</p><p className="text-[9px] font-bold tracking-[.22em] text-[hsl(var(--drawer-muted))]">BEAUTY DRAWER</p></div></div><button type="button" onClick={() => setSheetOpen(true)} className="flex h-11 items-center gap-2 rounded-xl bg-[hsl(var(--drawer-coral))] px-4 text-sm font-extrabold text-white"><Plus size={18} />新增</button></header>
  <section className="organize-in organize-delay-1 mt-7 rounded-[27px] bg-[hsl(var(--drawer-ink))] p-5 text-white drawer-shadow sm:p-7"><div className="flex items-start justify-between"><div><p className="text-[11px] font-bold tracking-[.16em] text-[hsl(var(--drawer-aqua))]">今日抽屜狀態</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">一眼找到，<span className="text-[hsl(var(--drawer-lime))]">剛剛好。</span></h1></div><ArrowDownUp className="text-[hsl(var(--drawer-aqua))]" size={22} /></div><div className="mt-7 flex items-end justify-between"><div><strong className="text-5xl font-black">{total}</strong><span className="ml-2 text-sm text-white/60">件存貨</span></div><div className="text-right text-xs text-white/60"><p>{products.length} 件商品</p><p className="mt-1 text-[hsl(var(--drawer-lime))]">{low} 件需要留意</p></div></div></section>
  <section className="organize-in organize-delay-2 mt-7"><div className="flex items-end justify-between"><div><p className="text-[10px] font-bold tracking-[.18em] text-[hsl(var(--drawer-coral))]">我的收藏</p><h2 className="mt-1 text-2xl font-black">抽屜裡有什麼</h2></div><span className="rounded-full bg-[hsl(var(--drawer-panel))] px-3 py-1.5 text-xs font-bold text-[hsl(var(--drawer-muted))]">{filtered.length} 件</span></div><div className="mt-5 flex gap-2 overflow-x-auto pb-1" role="tablist" aria-label="商品分類">{CATEGORIES.map(c => <button key={c} type="button" role="tab" aria-selected={category === c} onClick={() => setCategory(c)} className={`shrink-0 rounded-full px-4 py-2 text-xs font-extrabold ${category === c ? 'bg-[hsl(var(--drawer-ink))] text-white' : 'bg-[hsl(var(--drawer-panel))] text-[hsl(var(--drawer-muted))]'}`}>{c}</button>)}</div><div className="relative mt-4"><Search size={17} className="pointer-events-none absolute left-3.5 top-1/2 -translate-y-1/2 text-[hsl(var(--drawer-muted))]" /><label htmlFor="organized-search" className="sr-only">搜尋商品</label><input id="organized-search" value={query} onChange={e => setQuery(e.target.value)} placeholder="搜尋商品名稱" className="h-11 w-full rounded-xl border border-[hsl(var(--drawer-line))] bg-[hsl(var(--drawer-panel))] pl-10 pr-10 text-sm outline-none focus:border-[hsl(var(--drawer-coral))]" /><SlidersHorizontal size={16} className="pointer-events-none absolute right-3.5 top-1/2 -translate-y-1/2 text-[hsl(var(--drawer-muted))]" /></div></section>
  {products.length === 0 ? <section className="mt-6 flex min-h-[380px] flex-col items-center justify-center rounded-[26px] border border-dashed border-[hsl(var(--drawer-coral)/.35)] bg-[hsl(7_78%_59%/.05)] text-center"><Archive size={35} className="mb-5 text-[hsl(var(--drawer-coral))]" /><h3 className="text-xl font-black">抽屜現在是空的</h3><p className="mt-2 text-sm text-[hsl(var(--drawer-muted))]">把常用的保養和彩妝收進來，之後找東西會更快。</p><button type="button" onClick={() => setSheetOpen(true)} className="mt-5 rounded-xl bg-[hsl(var(--drawer-coral))] px-5 py-3 text-sm font-extrabold text-white">新增第一件商品</button></section> : filtered.length === 0 ? <section className="mt-6 flex min-h-[230px] flex-col items-center justify-center rounded-[26px] bg-[hsl(var(--drawer-panel))] text-center"><Search size={28} className="text-[hsl(var(--drawer-muted))]" /><p className="mt-3 font-bold">找不到相符商品</p><button type="button" onClick={() => { setQuery(''); setCategory('全部'); }} className="mt-3 text-xs font-bold text-[hsl(var(--drawer-coral))]">清除篩選</button></section> : <div className="organize-in organize-delay-3 mt-6 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">{filtered.map(p => <ProductTile key={p.id} product={p} onChange={n => update(p.id, n)} onDelete={() => setDeleteTarget(p)} />)}</div>}<footer className="mt-8 flex justify-between border-t border-[hsl(var(--drawer-line))] pt-5 text-xs text-[hsl(var(--drawer-muted))]"><span className="flex items-center gap-1.5"><Check size={14} />每一件都記得很清楚</span><span className="font-bold">收納完成</span></footer></div></main>{sheetOpen && <AddSheet onAdd={p => setProducts(ps => [p, ...ps])} onClose={() => setSheetOpen(false)} />}{deleteTarget && <DeleteDialog product={deleteTarget} onCancel={() => setDeleteTarget(null)} onConfirm={() => { setProducts(ps => ps.filter(p => p.id !== deleteTarget.id)); setDeleteTarget(null); }} />}</div>;
}